<% socket = `mysql_config --socket`.rstrip %>

development: &development
  adapter: mysql
  host: localhost
  socket: <%= socket %>
  database: rubyminds
  username: root
  password:

test:
  database: rubyminds_test
  <<: *development

production:
  database: rubyminds_production
  <<: *development
